#ifndef SPI_TMC_H
#define SPI_TMC_H

//#include "gd32f10x.h"
#include "main.h"

//CS1
#define TMC_CS1_H HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_SET)
#define TMC_CS1_L HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_RESET)
//CS2
#define TMC_CS2_H HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_SET)
#define TMC_CS2_L HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_RESET)
//CS3
#define TMC_CS3_H HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_SET)
#define TMC_CS3_L HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_RESET)
//CS4
#define TMC_CS4_H HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_SET)
#define TMC_CS4_L HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_RESET)
//CS5
#define TMC_CS5_H HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_SET)
#define TMC_CS5_L HAL_GPIO_WritePin(TMC5160_CSN_GPIO_Port, TMC5160_CSN_Pin, GPIO_PIN_RESET)


//SDI
#define TMC_SDI_H HAL_GPIO_WritePin(TMC5160_SDI_GPIO_Port, TMC5160_SDI_Pin, GPIO_PIN_SET)
#define TMC_SDI_L HAL_GPIO_WritePin(TMC5160_SDI_GPIO_Port, TMC5160_SDI_Pin, GPIO_PIN_RESET)
//SCLK
#define TMC_SCLK_H HAL_GPIO_WritePin(TMC5160_SCK_GPIO_Port, TMC5160_SCK_Pin, GPIO_PIN_SET)
#define TMC_SCLK_L HAL_GPIO_WritePin(TMC5160_SCK_GPIO_Port, TMC5160_SCK_Pin, GPIO_PIN_RESET)
//SDO
#define TMC_SDO_HorL HAL_GPIO_ReadPin(TMC5160_SDO_GPIO_Port, TMC5160_SDO_Pin)
#define TMC_SDO1_HorL HAL_GPIO_ReadPin(TMC5160_SDO_GPIO_Port, TMC5160_SDO_Pin)
#define TMC_SDO2_HorL HAL_GPIO_ReadPin(TMC5160_SDO_GPIO_Port, TMC5160_SDO_Pin)
#define TMC_SDO3_HorL HAL_GPIO_ReadPin(TMC5160_SDO_GPIO_Port, TMC5160_SDO_Pin)
#define TMC_SDO4_HorL HAL_GPIO_ReadPin(TMC5160_SDO_GPIO_Port, TMC5160_SDO_Pin)
#define TMC_SDO5_HorL HAL_GPIO_ReadPin(TMC5160_SDO_GPIO_Port, TMC5160_SDO_Pin)
extern uint8_t tmc_sdo_data[5];
 
#define MOTOR0 0 // Motor 0
void tmc_spi_init(void);
uint8_t tmc_spi_readwritebyte(uint8_t data);
uint8_t tmc_spi_sendbyte(uint8_t byte);
#endif /* SPI_TMC_H */

